# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['bottom' '2' 'top' '2' 'top' 'top' 'top' 'top' 'top' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [8]:
# Місце для Вашого коду

print(np.random.choice(10))

6


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [9]:
# Місце для Вашого коду

print(np.random.choice(10, size=(4,6)))

[[8 5 1 2 8 3]
 [7 4 0 2 5 2]
 [5 3 7 6 7 9]
 [6 4 3 9 2 1]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [10]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 1 4 3 4 0 4 3 1 1]


Згенеруйте одну випадкову цифру.

In [11]:
# Місце для Вашого коду

print(np.random.randint(10))

5


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [12]:
# Місце для Вашого коду

print(np.random.randint(low=10, high=100, size=(4,5)))

[[25 38 49 35 66]
 [21 19 37 60 17]
 [91 21 36 43 56]
 [75 42 19 51 69]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [13]:
# Місце для Вашого коду

print(np.random.sample(size=(3,4)))

[[0.8644747  0.15795498 0.94929154 0.8136696 ]
 [0.82091781 0.57188546 0.44374024 0.14110179]
 [0.39694406 0.40461635 0.30531267 0.09507516]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [14]:
a = 3
b = 5

In [16]:
# Місце для Вашого коду

print((b - a) * np.random.sample(size=10) + a)

[3.71156202 4.44205847 3.97926786 4.43499643 4.49501651 3.87480286
 4.1653885  4.611262   4.29070116 3.57760694]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [18]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[1 4 5 0 7 8 9 6 2 3]


Перетасуйте матрицю $M$.

In [19]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
# Місце для Вашого коду

np.random.shuffle(M)
print(M)

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [21]:
np.random.seed(42)

In [22]:
print(np.random.randint(10))

6


In [23]:
print(np.random.randint(10))

3


In [24]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [25]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [28]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'H']


In [29]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

6 heads and 4 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [34]:
# Місце для Вашого коду

tosses = np.random.choice(["H","T"], size=100)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

48 heads and 52 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [35]:
# Місце для Вашого коду

tosses = np.random.randint(2, size=100)
print("{} heads and {} tails".format(sum(tosses == 1),sum(tosses == 0)))

52 heads and 48 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [36]:
# Місце для Вашого коду

tosses = np.round(np.random.sample(100))
print("{} heads and {} tails".format(sum(tosses == 1),sum(tosses == 0)))

50 heads and 50 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [37]:
# Місце для Вашого коду

params = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]

for n in params:
    tosses = np.random.randint(2, size=n)
    heads_prob = sum(tosses == 1) / n
    tails_prob = sum(tosses == 0) / n
    print('n = {}  :  P(head) = {},  P(tail) = {}'.format(n, heads_prob, tails_prob))

n = 10  :  P(head) = 0.5,  P(tail) = 0.5
n = 50  :  P(head) = 0.46,  P(tail) = 0.54
n = 100  :  P(head) = 0.53,  P(tail) = 0.47
n = 250  :  P(head) = 0.456,  P(tail) = 0.544
n = 500  :  P(head) = 0.476,  P(tail) = 0.524
n = 1000  :  P(head) = 0.502,  P(tail) = 0.498
n = 2500  :  P(head) = 0.5004,  P(tail) = 0.4996
n = 5000  :  P(head) = 0.5026,  P(tail) = 0.4974
n = 10000  :  P(head) = 0.4983,  P(tail) = 0.5017


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [38]:
# Місце для Вашого коду

n_sides = 6
throughs = np.random.randint(n_sides, size=60)
for i in range(n_sides):
    print('Side {} : {}'.format(i, sum(throughs == i)))

Side 0 : 10
Side 1 : 10
Side 2 : 9
Side 3 : 12
Side 4 : 10
Side 5 : 9


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [45]:
# Місце для Вашого коду

params = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
n_sides = 6
print('Should be  :  1/6 = {}'.format(1/6))

for n in params:
    throughs = np.random.randint(n_sides, size=n)
    text = 'n = {}  :'.format(n)
    for i in range(n_sides):
        text += '  P({}) = {},'.format(i, sum(throughs == i) / n)
    print(text)

Should be  :  1/6 = 0.16666666666666666
n = 10  :  P(0) = 0.0,  P(1) = 0.2,  P(2) = 0.1,  P(3) = 0.1,  P(4) = 0.3,  P(5) = 0.3,
n = 50  :  P(0) = 0.18,  P(1) = 0.12,  P(2) = 0.26,  P(3) = 0.16,  P(4) = 0.16,  P(5) = 0.12,
n = 100  :  P(0) = 0.18,  P(1) = 0.14,  P(2) = 0.09,  P(3) = 0.18,  P(4) = 0.23,  P(5) = 0.18,
n = 250  :  P(0) = 0.172,  P(1) = 0.16,  P(2) = 0.172,  P(3) = 0.168,  P(4) = 0.196,  P(5) = 0.132,
n = 500  :  P(0) = 0.146,  P(1) = 0.144,  P(2) = 0.164,  P(3) = 0.204,  P(4) = 0.146,  P(5) = 0.196,
n = 1000  :  P(0) = 0.154,  P(1) = 0.17,  P(2) = 0.153,  P(3) = 0.18,  P(4) = 0.174,  P(5) = 0.169,
n = 2500  :  P(0) = 0.1716,  P(1) = 0.1672,  P(2) = 0.158,  P(3) = 0.1672,  P(4) = 0.172,  P(5) = 0.164,
n = 5000  :  P(0) = 0.1672,  P(1) = 0.1634,  P(2) = 0.1708,  P(3) = 0.1584,  P(4) = 0.1726,  P(5) = 0.1676,
n = 10000  :  P(0) = 0.1689,  P(1) = 0.1652,  P(2) = 0.1651,  P(3) = 0.1647,  P(4) = 0.1667,  P(5) = 0.1694,


## 5 Колода карт
### 5.1 Реалізація

In [41]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('2', '♡'), ('2', '♣'), ('2', '♠'), ('2', '♢'), ('9', '♡'), ('9', '♣'), ('9', '♠'), ('9', '♢'), ('10', '♡'), ('10', '♣'), ('10', '♠'), ('10', '♢'), ('Q', '♡'), ('Q', '♣'), ('Q', '♠'), ('Q', '♢'), ('7', '♡'), ('7', '♣'), ('7', '♠'), ('7', '♢'), ('8', '♡'), ('8', '♣'), ('8', '♠'), ('8', '♢'), ('K', '♡'), ('K', '♣'), ('K', '♠'), ('K', '♢'), ('6', '♡'), ('6', '♣'), ('6', '♠'), ('6', '♢'), ('5', '♡'), ('5', '♣'), ('5', '♠'), ('5', '♢'), ('1', '♡'), ('1', '♣'), ('1', '♠'), ('1', '♢'), ('J', '♡'), ('J', '♣'), ('J', '♠'), ('J', '♢'), ('4', '♡'), ('4', '♣'), ('4', '♠'), ('4', '♢'), ('3', '♡'), ('3', '♣'), ('3', '♠'), ('3', '♢')]


In [42]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

2♡, 2♣, 2♠, 2♢, 9♡, 9♣, 9♠, 9♢, 10♡, 10♣, 10♠, 10♢, Q♡, Q♣, Q♠, Q♢, 7♡, 7♣, 7♠, 7♢, 8♡, 8♣, 8♠, 8♢, K♡, K♣, K♠, K♢, 6♡, 6♣, 6♠, 6♢, 5♡, 5♣, 5♠, 5♢, 1♡, 1♣, 1♠, 1♢, J♡, J♣, J♠, J♢, 4♡, 4♣, 4♠, 4♢, 3♡, 3♣, 3♠, 3♢


In [43]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♡2, ♡9, ♡10, ♡Q, ♡7, ♡8, ♡K, ♡6, ♡5, ♡1, ♡J, ♡4, ♡3
♣2, ♣9, ♣10, ♣Q, ♣7, ♣8, ♣K, ♣6, ♣5, ♣1, ♣J, ♣4, ♣3
♠2, ♠9, ♠10, ♠Q, ♠7, ♠8, ♠K, ♠6, ♠5, ♠1, ♠J, ♠4, ♠3
♢2, ♢9, ♢10, ♢Q, ♢7, ♢8, ♢K, ♢6, ♢5, ♢1, ♢J, ♢4, ♢3


In [44]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('K', '♠'), ('4', '♡'), ('7', '♢'), ('2', '♠'), ('6', '♣'), ('3', '♡'), ('7', '♠'), ('J', '♠'), ('J', '♣'), ('1', '♡'), ('4', '♢'), ('Q', '♣'), ('6', '♢'), ('K', '♡'), ('10', '♡'), ('2', '♡'), ('K', '♢'), ('8', '♠'), ('5', '♣'), ('9', '♡'), ('10', '♢'), ('10', '♠'), ('4', '♠'), ('J', '♡'), ('8', '♢'), ('6', '♠'), ('5', '♡'), ('9', '♣'), ('J', '♢'), ('6', '♡'), ('3', '♢'), ('9', '♢'), ('Q', '♢'), ('3', '♠'), ('4', '♣'), ('10', '♣'), ('9', '♠'), ('2', '♢'), ('K', '♣'), ('8', '♡'), ('1', '♢'), ('8', '♣'), ('3', '♣'), ('7', '♡'), ('5', '♠'), ('Q', '♠'), ('7', '♣'), ('1', '♣'), ('5', '♢'), ('Q', '♡'), ('1', '♠'), ('2', '♣')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [50]:
# Місце для Вашого коду

print('Should be  :  20/52 = 5/13 = {}'.format(5/13))

params = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]

for n in params:
    indices = np.random.randint(52, size=n)
    cards = [Cards[i] for i in indices]
    rangs = [card[0] for card in cards]
    k = 0
    for rang in rangs:
        if rang in [str(x) for x in np.arange(2, 11, 2)]:
            k += 1
    text = 'n = {}  :  P(2, 4, 6, 8, 10) = {}'.format(n, k/n)
    print(text)

Should be  :  20/52 = 5/13 = 0.38461538461538464
n = 10  :  P(2, 4, 6, 8, 10) = 0.6
n = 50  :  P(2, 4, 6, 8, 10) = 0.44
n = 100  :  P(2, 4, 6, 8, 10) = 0.39
n = 250  :  P(2, 4, 6, 8, 10) = 0.344
n = 500  :  P(2, 4, 6, 8, 10) = 0.402
n = 1000  :  P(2, 4, 6, 8, 10) = 0.357
n = 2500  :  P(2, 4, 6, 8, 10) = 0.3884
n = 5000  :  P(2, 4, 6, 8, 10) = 0.3864
n = 10000  :  P(2, 4, 6, 8, 10) = 0.3873


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [ ]:
# Місце для Вашого коду

def check_condition(cards, show=False):
    players = np.reshape(cards, (4, 13, 2))
    for player in players:
        suits = [card[1] for card in player]
        nums = []
        for suit in Suits:
            nums.append(suits.count(suit))
        if show:
            text = 'Player cards  :'
            for i in range(4):
                text += '  suit {} = {},'.format(list(Suits)[i], nums[i])
            print(text)
            print([tuple(card) for card in player])
            print('='*100)
        if set(nums) != {3, 4}:
            return False
    return True

In [101]:
n = 1
np.random.shuffle(Cards)
while not check_condition(Cards):
    np.random.shuffle(Cards)
    n += 1
print('n = {}'.format(n))
print('='*100)
check_condition(Cards, show=True)

n = 1654
Player cards  :  suit ♡ = 3,  suit ♣ = 4,  suit ♠ = 3,  suit ♢ = 3,
[('2', '♢'), ('5', '♡'), ('1', '♣'), ('6', '♣'), ('Q', '♠'), ('6', '♡'), ('9', '♠'), ('K', '♢'), ('4', '♡'), ('4', '♣'), ('3', '♢'), ('7', '♠'), ('9', '♣')]
Player cards  :  suit ♡ = 4,  suit ♣ = 3,  suit ♠ = 3,  suit ♢ = 3,
[('9', '♡'), ('8', '♣'), ('7', '♣'), ('Q', '♢'), ('9', '♢'), ('5', '♢'), ('2', '♠'), ('K', '♡'), ('3', '♠'), ('8', '♠'), ('Q', '♣'), ('8', '♡'), ('10', '♡')]
Player cards  :  suit ♡ = 3,  suit ♣ = 3,  suit ♠ = 3,  suit ♢ = 4,
[('J', '♣'), ('1', '♠'), ('3', '♡'), ('2', '♣'), ('J', '♡'), ('10', '♢'), ('7', '♢'), ('4', '♠'), ('1', '♢'), ('2', '♡'), ('8', '♢'), ('10', '♠'), ('K', '♣')]
Player cards  :  suit ♡ = 3,  suit ♣ = 3,  suit ♠ = 4,  suit ♢ = 3,
[('10', '♣'), ('6', '♢'), ('1', '♡'), ('Q', '♡'), ('5', '♠'), ('3', '♣'), ('J', '♢'), ('4', '♢'), ('K', '♠'), ('6', '♠'), ('5', '♣'), ('J', '♠'), ('7', '♡')]


True

In [120]:
players = [[], [], [], []]
player_counter = 0

for i in np.random.choice(4, size=4, replace=False):
    suit = list(Suits)[i]
    cards = [(rank, suit) for rank in Ranks]
    np.random.shuffle(cards)
    k = 0
    for j in range(len(players)):
        if player_counter == j:
            for _ in range(4):
                players[j].append(cards[k])
                k += 1
        else:
            for _ in range(3):
                players[j].append(cards[k])
                k += 1
    player_counter += 1

for i in range(len(players)):
    np.random.shuffle(players[i])

check_condition(np.reshape(players, (1, 52, 2)), show=True)

Player cards  :  suit ♡ = 3,  suit ♣ = 4,  suit ♠ = 3,  suit ♢ = 3,
[('5', '♠'), ('3', '♡'), ('10', '♢'), ('1', '♣'), ('J', '♣'), ('7', '♠'), ('K', '♣'), ('4', '♡'), ('6', '♡'), ('2', '♣'), ('1', '♢'), ('8', '♠'), ('5', '♢')]
Player cards  :  suit ♡ = 3,  suit ♣ = 3,  suit ♠ = 4,  suit ♢ = 3,
[('4', '♠'), ('8', '♡'), ('J', '♠'), ('2', '♡'), ('Q', '♢'), ('6', '♢'), ('4', '♣'), ('K', '♢'), ('5', '♡'), ('3', '♣'), ('K', '♠'), ('7', '♣'), ('3', '♠')]
Player cards  :  suit ♡ = 3,  suit ♣ = 3,  suit ♠ = 3,  suit ♢ = 4,
[('7', '♢'), ('9', '♣'), ('Q', '♡'), ('2', '♠'), ('Q', '♣'), ('4', '♢'), ('10', '♠'), ('J', '♡'), ('9', '♡'), ('1', '♠'), ('J', '♢'), ('9', '♢'), ('5', '♣')]
Player cards  :  suit ♡ = 4,  suit ♣ = 3,  suit ♠ = 3,  suit ♢ = 3,
[('8', '♣'), ('10', '♣'), ('Q', '♠'), ('7', '♡'), ('9', '♠'), ('3', '♢'), ('6', '♣'), ('2', '♢'), ('6', '♠'), ('K', '♡'), ('10', '♡'), ('8', '♢'), ('1', '♡')]


True

### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [121]:
# Місце для Вашого коду

def check_condition(cards, show=False):
    players = np.reshape(cards, (4, 13, 2))
    for player in players:
        suits = [card[1] for card in player]
        nums = []
        for suit in Suits:
            nums.append(suits.count(suit))
        if show:
            text = 'Player cards  :'
            for i in range(4):
                text += '  suit {} = {},'.format(list(Suits)[i], nums[i])
            print(text)
            print([tuple(card) for card in player])
            print('='*100)
        for num in nums:
            if num < 2 or num > 5:
                return False
    return True

In [175]:
n = 1
np.random.shuffle(Cards)
while not check_condition(Cards):
    np.random.shuffle(Cards)
    n += 1
print('n = {}'.format(n))
print('='*100)
check_condition(Cards, show=True)

n = 9
Player cards  :  suit ♡ = 4,  suit ♣ = 2,  suit ♠ = 3,  suit ♢ = 4,
[('3', '♡'), ('9', '♢'), ('2', '♡'), ('K', '♠'), ('6', '♣'), ('J', '♣'), ('J', '♡'), ('8', '♠'), ('3', '♢'), ('8', '♡'), ('3', '♠'), ('K', '♢'), ('J', '♢')]
Player cards  :  suit ♡ = 3,  suit ♣ = 4,  suit ♠ = 3,  suit ♢ = 3,
[('J', '♠'), ('Q', '♡'), ('4', '♡'), ('8', '♢'), ('9', '♠'), ('9', '♣'), ('Q', '♣'), ('2', '♢'), ('7', '♢'), ('7', '♡'), ('4', '♣'), ('7', '♣'), ('2', '♠')]
Player cards  :  suit ♡ = 3,  suit ♣ = 3,  suit ♠ = 3,  suit ♢ = 4,
[('Q', '♠'), ('Q', '♢'), ('5', '♣'), ('6', '♠'), ('1', '♢'), ('5', '♢'), ('1', '♣'), ('10', '♣'), ('9', '♡'), ('1', '♡'), ('4', '♢'), ('1', '♠'), ('6', '♡')]
Player cards  :  suit ♡ = 3,  suit ♣ = 4,  suit ♠ = 4,  suit ♢ = 2,
[('7', '♠'), ('10', '♠'), ('4', '♠'), ('10', '♢'), ('3', '♣'), ('10', '♡'), ('6', '♢'), ('8', '♣'), ('2', '♣'), ('5', '♠'), ('K', '♡'), ('5', '♡'), ('K', '♣')]


True

In [363]:
def replace_one_card(players, suit_nums):
    for i in range(len(suit_nums)):
        for j in range(len(suit_nums[0])):
            if suit_nums[i][j] == 5 and sum(suit_nums[i]) < 13:
                player_index = i
                suit_index = j
    min_set = set()
    for j in range(len(suit_nums[0])):
        if suit_nums[player_index][j] == min(suit_nums[player_index]):
            min_set.add(j)
    for i in np.random.choice(4, size=4, replace=False):
        if suit_nums[i][suit_index] == 2:
            player_2_index = i
            break
    max_set = set()
    for j in range(len(suit_nums[0])):
        if suit_nums[player_2_index][j] == max(suit_nums[player_2_index]):
            max_set.add(j)
    try:
        suit_2_index = list(min_set.intersection(max_set))[0]
    except:
        suit_2_index = list(max_set)[0]
    for i in range(len(players[player_index])):
        if players[player_index][i][1] == list(Suits)[suit_index]:
            card_1 = players[player_index].pop(i)
            break
    for i in range(len(players[player_2_index])):
        if players[player_2_index][i][1] == list(Suits)[suit_2_index]:
            card_2 = players[player_2_index].pop(i)
            break
    players[player_index].append(card_2)
    players[player_2_index].append(card_1)
    # print('player index : ', player_index)
    # print('suit index : ', suit_index)
    # print('player 2 index : ', player_2_index)
    # print('suit 2 index : ', suit_2_index)
    # print('card 1 : ', card_1)
    # print('card 2 : ', card_2)
    return players, player_index, suit_index

def calculate_suit_nums(players):
    suit_nums = [[0,0,0,0] for _ in range(len(players))]
    for i in range(len(players)):
        for card in players[i]:
            for j in range(len(Suits)):
                if card[1] == list(Suits)[j]:
                    suit_nums[i][j] += 1
    return suit_nums

In [370]:
res = []
for _ in range(1):
    players = [[], [], [], []]
    cards_left = []

    for i in np.random.choice(4, size=4, replace=False):
        suit = list(Suits)[i]
        cards = [(rank, suit) for rank in Ranks]
        np.random.shuffle(cards)
        k = 0
        for j in range(len(players)):
            for _ in range(2):
                players[j].append(cards[k])
                k += 1
        for _ in range(5):
            cards_left.append(cards[k])
            k += 1

    nums = [8,8,8,8]
    suit_nums = [[2,2,2,2], [2,2,2,2], [2,2,2,2], [2,2,2,2]]
    players_set = {0,1,2,3}
    counter = 0
    suit_sets = [set(), set(), set(), set()]

    for card in cards_left:
        # print('counter : ', counter)
        # print('players set : ', players_set)
        for i in range(len(Suits)):
            if list(Suits)[i] == card[1]:
                suit_index = i
        # print('suit index : ', suit_index)
        # print('suit sets : ', suit_sets)
        if len(players_set-suit_sets[suit_index]) == 0:
            # print('Made replacement')
            players, p_ind, s_ind = replace_one_card(players, suit_nums)
            suit_nums = calculate_suit_nums(players)
            suit_sets[suit_index] -= {p_ind}
            # print('='*100)
        player_index = np.random.choice(list(players_set-suit_sets[suit_index]))
        # print('player index : ', player_index)
        players[player_index].append(card)
        nums[player_index] += 1
        suit_nums[player_index][suit_index] += 1
        # print('nums : ', nums)
        # print('suit nums : ', suit_nums)
        if suit_nums[player_index][suit_index] == 5:
            suit_sets[suit_index].add(player_index)
        if nums[player_index] == 13:
            players_set -= {player_index}
        counter += 1
        # print('='*100)

    for i in range(len(players)):
        np.random.shuffle(players[i])

    # res.append(check_condition(np.reshape(players, (1, 52, 2)), show=False))
    check_condition(np.reshape(players, (1, 52, 2)), show=True)
    if not check_condition(np.reshape(players, (1, 52, 2)), show=False):
        check_condition(np.reshape(players, (1, 52, 2)), show=True)
        break

Player cards  :  suit ♡ = 5,  suit ♣ = 2,  suit ♠ = 3,  suit ♢ = 3,
[('5', '♢'), ('7', '♡'), ('1', '♡'), ('3', '♣'), ('4', '♠'), ('4', '♡'), ('6', '♢'), ('3', '♢'), ('Q', '♡'), ('5', '♣'), ('3', '♠'), ('9', '♡'), ('8', '♠')]
Player cards  :  suit ♡ = 4,  suit ♣ = 4,  suit ♠ = 2,  suit ♢ = 3,
[('J', '♢'), ('3', '♡'), ('7', '♠'), ('6', '♡'), ('1', '♠'), ('J', '♣'), ('7', '♣'), ('10', '♡'), ('8', '♣'), ('1', '♣'), ('2', '♡'), ('9', '♢'), ('2', '♢')]
Player cards  :  suit ♡ = 2,  suit ♣ = 2,  suit ♠ = 4,  suit ♢ = 5,
[('5', '♠'), ('8', '♡'), ('Q', '♠'), ('K', '♠'), ('8', '♢'), ('Q', '♢'), ('9', '♠'), ('J', '♡'), ('K', '♢'), ('4', '♢'), ('Q', '♣'), ('1', '♢'), ('6', '♣')]
Player cards  :  suit ♡ = 2,  suit ♣ = 5,  suit ♠ = 4,  suit ♢ = 2,
[('7', '♢'), ('6', '♠'), ('2', '♣'), ('10', '♠'), ('4', '♣'), ('5', '♡'), ('J', '♠'), ('9', '♣'), ('K', '♡'), ('K', '♣'), ('2', '♠'), ('10', '♢'), ('10', '♣')]


In [369]:
all(res)

True